### ISSUE TITLE
Add Child of Light

### ISSUE THREAD

**Issue by patrickpissurno** [Haoose/UPLAY_GAME_ID#5]
Hi,

Had trouble finding the id for Child of Light, but finally did it: it's **609**.

You might want to add it to your list.

Thanks!

**Comment by xalron** [comment]
Also 44 is Heroes VI

**Comment by Lethaltail** [comment]
This is a bit of a shot but could anyone point me in the direction of how to finesse a game ID out of the client? I've had "Tom Clancy's The Division 2 - PPS" sitting in here (though deactivated) for a little over 2 years and I think it would do good to note it here.

**Comment by Haoose** [comment]
@Lethaltail Yes, you can do it.
To do this, start the Uplay client and (for example) Cheat Engine.
Then open the game with a known ID. And find it in the client's memory. Repeat the procedure several times until there are several addresses left.
Finally, open your game and you will find out its ID.
Enjoy ;)
